# Temel Bilgiler
title: "patirota"
email: "info@patirota.com"
description: >-
  Köpeğinizin enerjisini güvenle ve keyifle harcaması için profesyonel köpek yürüyüş hizmeti. 
  Patirota ile yürüyüş, sadık dostlar için özgürlük demektir!
baseurl: "" 
url: "https://patirota.github.io"  # Sitenin adresi

# Yazar bilgileri
author: "PatiRota"

# Sosyal medya bağlantıları (İstersen ekle)
social:
  instagram: "https://instagram.com/patirotacom"
  whatsapp: "https://wa.me/905055095224"

# Tema ayarları
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title

# Tema
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

# SEO etiketleri
plugins:
  - jekyll-feed
  - jekyll-seo-tag
